version: "3.9"

networks:
  tom:
    driver: bridge

services:
  tom:
    build:
      context: .
      dockerfile: ./dockerfiles/tom/Dockerfile
    container_name: tom
    restart: always
    ports:
      - "443:443"
    volumes:
      - /data/:/data/
    networks:
      - tom

  mickael:
    build:
      context: .
      dockerfile: ./dockerfiles/agent/Dockerfile
    container_name: mickael
    restart: always
    environment:
      - TOM_USERNAME=mickael
    networks:
      - tom
    volumes:
      - /data/:/data/

  nina:
    build:
      context: .
      dockerfile: ./dockerfiles/agent/Dockerfile
    container_name: nina
    restart: always
    environment:
      - TOM_USERNAME=nina
    networks:
      - tom
    volumes:
      - /data/:/data/

  ambre:
    build:
      context: .
      dockerfile: ./dockerfiles/agent/Dockerfile
    container_name: ambre
    restart: always
    environment:
      - TOM_USERNAME=ambre
    networks:
      - tom
    volumes:
      - /data/:/data/

  charlotte:
    build:
      context: .
      dockerfile: ./dockerfiles/agent/Dockerfile
    container_name: charlotte
    restart: always
    environment:
      - TOM_USERNAME=charlotte
    networks:
      - tom
    volumes:
      - /data/:/data/


### MODULES MCP ###
  # Global
  weather:
    build:
      context: .
      dockerfile: ./dockerfiles/mcp/weather/Dockerfile
    container_name: weather
    restart: always
    environment:
      - TOM_LOG_LEVEL=DEBUG
    networks:
      - tom
    volumes:
      - /data/mcp/weather/:/data/
 
  weather:
    build:
      context: .
      dockerfile: ./dockerfiles/mcp/weather/Dockerfile
    container_name: weather
    restart: always
    environment:
      - TOM_LOG_LEVEL=DEBUG
    networks:
      - tom
    volumes:
      - /data/mcp/weather/:/data/
  
  contacts:
    build:
      context: .
      dockerfile: ./dockerfiles/mcp/contacts/Dockerfile
    container_name: contacts
    restart: always
    environment:
      - TOM_LOG_LEVEL=DEBUG
    networks:
      - tom
    volumes:
      - /data/mcp/contacts/:/data/
  

  # Personal
 
  anki-mickael:
    build:
      context: .
      dockerfile: ./dockerfiles/mcp/anki/Dockerfile
    container_name: anki-mickael
    restart: always
    environment:
      - TOM_LOG_LEVEL=DEBUG
      - ANKI_URL=http://server.taila2494.ts.net:8765
      - ANKI_PROFILE=mickael
    networks:
      - tom
    volumes:
      - /data/mcp/anki/:/data/

  calendar-mickael:
    build:
      context: .
      dockerfile: ./dockerfiles/mcp/calendar/Dockerfile
    container_name: calendar-mickael
    restart: always
    environment:
      - TOM_LOG_LEVEL=DEBUG
      - TOM_USER=mickael
    networks:
      - tom
    volumes:
      - /data/mcp/calendar/:/data/

  calendar-nina:
    build:
      context: .
      dockerfile: ./dockerfiles/mcp/calendar/Dockerfile
    container_name: calendar-nina
    restart: always
    environment:
      - TOM_LOG_LEVEL=DEBUG
      - TOM_USER=nina
    networks:
      - tom
    volumes:
      - /data/mcp/calendar/:/data/

  calendar-ambre:
    build:
      context: .
      dockerfile: ./dockerfiles/mcp/calendar/Dockerfile
    container_name: calendar-ambre
    restart: always
    environment:
      - TOM_LOG_LEVEL=DEBUG
      - TOM_USER=ambre
    networks:
      - tom
    volumes:
      - /data/mcp/calendar/:/data/

